export const PRICING_IDS = {
  LOCAL: {
    MONTHLY: {
      INDICATORS_SINGLE_NT: "price_1Rk96ZDHqntRcM5inO0o24TP",
      INDICATORS_SINGLE_TV: "price_1SCOHuDHqntRcM5igLxXPiS0",
      INDICATORS_BOTH: "price_1SCOIPDHqntRcM5iITNhbT1z",
      STRATEGIES_SINGLE_NT: "price_1Rk971DHqntRcM5i5pndgfLL",
      STRATEGIES_SINGLE_TV: "price_1SROS6DHqntRcM5inP7na4xA",
      STRATEGIES_BOTH: "price_1SCOIgDHqntRcM5ilbjDXU7y",
      TEST: "price_1RuGDIDHqntRcM5iboesQtD5",
    },
    QUARTERLY: {
      INDICATORS_SINGLE_NT: "price_1SRON8DHqntRcM5iRsZ1dyfY",
      INDICATORS_SINGLE_TV: "price_1SROOwDHqntRcM5ij76tS9GM",
      INDICATORS_BOTH: "price_1SROTQDHqntRcM5i0aBM6htt",
      STRATEGIES_SINGLE_NT: "price_1SROOLDHqntRcM5ibt6eXz2V",
      STRATEGIES_SINGLE_TV: "price_1SROQ2DHqntRcM5i5jcqM9De",
      STRATEGIES_BOTH: "price_1SROUDDHqntRcM5iEtP8oTdK",
      TEST: "price_1SReY6DHqntRcM5iSfDXxlbC",
    },
    YEARLY: {
      INDICATORS_SINGLE_NT: "price_1SRON8DHqntRcM5i7dR2zA5h",
      INDICATORS_SINGLE_TV: "price_1SROOwDHqntRcM5iI0GteJvi",
      INDICATORS_BOTH: "price_1SROTQDHqntRcM5i74fxYVGa",
      STRATEGIES_SINGLE_NT: "price_1SROOLDHqntRcM5iu5TZNX7b",
      STRATEGIES_SINGLE_TV: "price_1SROQ2DHqntRcM5iGauOu3Na",
      STRATEGIES_BOTH: "price_1SROUDDHqntRcM5it9Hg0L3m",
      TEST: "price_1SReYEDHqntRcM5is68aYZ0C",
    },
  },
  PRODUCTION: {
    MONTHLY: {
      INDICATORS_SINGLE_NT: "price_1RkWkiDHqntRcM5i8UrCeTsw",
      INDICATORS_SINGLE_TV: "price_1SCOEzDHqntRcM5iSPtrtetG",
      INDICATORS_BOTH: "price_1SCOG5DHqntRcM5iouL0zesB",
      STRATEGIES_SINGLE_NT: "price_1RkWkcDHqntRcM5i4MakObtw",
      STRATEGIES_SINGLE_TV: "price_1SCOFJDHqntRcM5iMcAPakLT",
      STRATEGIES_BOTH: "price_1SCOGgDHqntRcM5irQtSptbE",
      TEST: "price_1RuG9KDHqntRcM5iW0OPXS5D",
    },
    QUARTERLY: {
      INDICATORS_SINGLE_NT: "PLACEHOLDER_QUARTERLY_INDICATORS_SINGLE_NT",
      INDICATORS_SINGLE_TV: "PLACEHOLDER_QUARTERLY_INDICATORS_SINGLE_TV",
      INDICATORS_BOTH: "PLACEHOLDER_QUARTERLY_INDICATORS_BOTH",
      STRATEGIES_SINGLE_NT: "PLACEHOLDER_QUARTERLY_STRATEGIES_SINGLE_NT",
      STRATEGIES_SINGLE_TV: "PLACEHOLDER_QUARTERLY_STRATEGIES_SINGLE_TV",
      STRATEGIES_BOTH: "PLACEHOLDER_QUARTERLY_STRATEGIES_BOTH",
      TEST: "PLACEHOLDER_QUARTERLY_TEST",
    },
    YEARLY: {
      INDICATORS_SINGLE_NT: "PLACEHOLDER_YEARLY_INDICATORS_SINGLE_NT",
      INDICATORS_SINGLE_TV: "PLACEHOLDER_YEARLY_INDICATORS_SINGLE_TV",
      INDICATORS_BOTH: "PLACEHOLDER_YEARLY_INDICATORS_BOTH",
      STRATEGIES_SINGLE_NT: "PLACEHOLDER_YEARLY_STRATEGIES_SINGLE_NT",
      STRATEGIES_SINGLE_TV: "PLACEHOLDER_YEARLY_STRATEGIES_SINGLE_TV",
      STRATEGIES_BOTH: "PLACEHOLDER_YEARLY_STRATEGIES_BOTH",
      TEST: "PLACEHOLDER_YEARLY_TEST",
    },
  },
};

// Pricing objects for each billing period
export const PRICING = {
  MONTHLY: {
    STRATEGIES_SINGLE: 99,
    STRATEGIES_BOTH: 119,
    INDICATORS_SINGLE: 49,
    INDICATORS_BOTH: 69,
  },
  QUARTERLY: {
    STRATEGIES_SINGLE: 265, // PLACEHOLDER - fill in quarterly price
    STRATEGIES_BOTH: 320, // PLACEHOLDER - fill in quarterly price
    INDICATORS_SINGLE: 130, // PLACEHOLDER - fill in quarterly price
    INDICATORS_BOTH: 185, // PLACEHOLDER - fill in quarterly price
  },
  YEARLY: {
    STRATEGIES_SINGLE: 990, // PLACEHOLDER - fill in yearly price
    STRATEGIES_BOTH: 1190, // PLACEHOLDER - fill in yearly price
    INDICATORS_SINGLE: 490, // PLACEHOLDER - fill in yearly price
    INDICATORS_BOTH: 690, // PLACEHOLDER - fill in yearly price
  },
};
